## Taller integrador

In [4]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\ryzen\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ryzen\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ryzen\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\ryzen\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\ryzen\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
import pandas as pd

#print(pd.__version__)

df = pd.read_csv("estudiantes2026.csv")
df

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera
5,Miguel Flores,37,Guadalajara,México,M,básico,4,4.1,1,False,2024-09-01,True,900,ascenso laboral
6,Laura Gómez,31,Cali,Colombia,F,básico,11,7.9,2,True,2024-09-01,False,0,cambio de carrera
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
8,Camila Vargas,33,Quito,Ecuador,F,básico,9,6.1,2,True,2024-09-01,True,700,primer empleo tech
9,Andrés Herrera,45,Barranquilla,Colombia,M,avanzado,5,7.2,2,True,2024-09-01,True,2500,emprendimiento
10,Paula Jiménez,27,Montevideo,Uruguay,F,básico,13,8.5,3,True,2024-09-01,False,0,cambio de carrera
11,Ricardo López,39,Caracas,Venezuela,M,intermedio,7,5.8,1,True,2024-09-01,True,600,cambio de carrera
12,Isabella Martínez,24,Medellín,Colombia,F,básico,16,9.4,3,True,2024-09-01,False,0,primer empleo tech
13,Fernando Díaz,52,Bogotá,Colombia,M,avanzado,3,NaN,0,False,2024-09-01,True,3200,emprendimiento
14,Natalia Romero,30,Cartagena,Colombia,F,intermedio,11,7.6,2,True,2024-09-01,True,1300,cambio de carrera
15,Diego Morales,28,La Paz,Bolivia,M,básico,10,6.4,2,True,2024-09-01,True,500,primer empleo tech
16,Sofía Reyes,35,Ciudad de México,México,F,intermedio,8,7.1,2,True,2024-09-01,True,1400,ascenso laboral
17,Alejandro Núñez,23,Bogotá,Colombia,M,básico,18,9.2,3,True,2024-09-01,False,0,primer empleo tech
18,Mariana Castillo,43,Asunción,Paraguay,F,avanzado,6,6.9,2,True,2024-09-01,True,1800,emprendimiento
19,Luis Prada,31,Cúcuta,Colombia,M,básico,9,NaN,1,True,2024-09-01,True,750,ascenso laboral
20,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
21,Andrea Fuentes,26,Bogotá,Colombia,F,intermedio,12,8.1,3,True,2024-09-01,False,0,cambio de carrera
22,Tomás Aguirre,38,Córdoba,Argentina,M,avanzado,5,7.8,2,True,2024-09-01,True,1900,emprendimiento
23,Valeria Peña,29,Bucaramanga,Colombia,F,básico,14,8.9,3,True,2024-09-01,False,0,primer empleo tech
24,José Moreno,47,Ciudad de Panamá,Panamá,M,intermedio,4,5.5,1,True,2024-09-01,True,2200,ascenso laboral

Pandas → Librerira python

Dataframe → Estructura que crea pandas cuando carga un cvs. Tiene por lo general filas y columnas

In [35]:
# shape devuelve (fila, columnas)
print(df.shape)

# nombres exactos de las columnas
print(df.columns.tolist())

(25, 14)
['nombre', 'edad', 'ciudad', 'pais', 'genero', 'nivel_previo', 'horas_estudio_semana', 'promedio', 'modulos_completados', 'activo', 'fecha_ingreso', 'trabaja_actualmente', 'salario_usd', 'objetivo']

In [36]:
df["nombre"]

0      Valentina Torres
1        Carlos Mendoza
2            Anita Ruiz
3         Jorge Ramírez
4          Daniela Soto
5         Miguel Flores
6           Laura Gómez
7      Sebastián Castro
8         Camila Vargas
9        Andrés Herrera
10        Paula Jiménez
11        Ricardo López
12    Isabella Martínez
13        Fernando Díaz
14       Natalia Romero
15        Diego Morales
16          Sofía Reyes
17      Alejandro Núñez
18     Mariana Castillo
19           Luis Prada
20       Carlos Mendoza
21       Andrea Fuentes
22        Tomás Aguirre
23         Valeria Peña
24          José Moreno
Name: nombre, dtype: str

In [37]:
df["edad"]

0     28
1     34
2     25
3     41
4     29
5     37
6     31
7     26
8     33
9     45
10    27
11    39
12    24
13    52
14    30
15    28
16    35
17    23
18    43
19    31
20    34
21    26
22    38
23    29
24    47
Name: edad, dtype: int64

In [38]:
print(df.loc[0,"nombre"])
print(df.loc[3,"promedio"])

Valentina Torres
7.4

In [39]:
df.head(10)
# me permite orientarme con respecto a la data que estoy trabajando

,nombre,edad,ciudad,pais,genero,nivel_previo,horas_estudio_semana,promedio,modulos_completados,activo,fecha_ingreso,trabaja_actualmente,salario_usd,objetivo
0,Valentina Torres,28,Bogotá,Colombia,F,intermedio,12,8.7,3,True,2024-09-01,True,1200,cambio de carrera
1,Carlos Mendoza,34,Ciudad de México,México,M,básico,8,5.2,1,True,2024-09-01,True,800,ascenso laboral
2,Anita Ruiz,25,Medellín,Colombia,F,básico,15,9.1,3,True,2024-09-01,False,0,primer empleo tech
3,Jorge Ramírez,41,Lima,Perú,M,avanzado,6,7.4,2,True,2024-09-01,True,2100,emprendimiento
4,Daniela Soto,29,Santiago,Chile,F,intermedio,10,6.8,2,True,2024-09-01,True,1500,cambio de carrera
5,Miguel Flores,37,Guadalajara,México,M,básico,4,4.1,1,False,2024-09-01,True,900,ascenso laboral
6,Laura Gómez,31,Cali,Colombia,F,básico,11,7.9,2,True,2024-09-01,False,0,cambio de carrera
7,Sebastián Castro,26,Buenos Aires,Argentina,M,intermedio,14,8.3,3,True,2024-09-01,True,1100,emprendimiento
8,Camila Vargas,33,Quito,Ecuador,F,básico,9,6.1,2,True,2024-09-01,True,700,primer empleo tech
9,Andrés Herrera,45,Barranquilla,Colombia,M,avanzado,5,7.2,2,True,2024-09-01,True,2500,emprendimiento

ver el ultimo nombre
print(df.loc[df.shape[0] -1, "nombre"])

In [14]:
print(df.loc[df.shape[0] -1, "nombre"])

Ricardo Rojas

In [16]:
# Calcula estadissticas importantes
# mean - media
# std - desviación estándar, que tan dispersos est[an los datos. Si es muy alto significa que son muy diferentes los datos
df.describe()

             id       edad  cursos_previos   promedio
count  20.00000  20.000000       20.000000  20.000000
mean   10.50000  34.100000        3.100000   6.705000
std     5.91608   5.901828        2.531902   1.814409
min     1.00000  27.000000        0.000000   3.700000
25%     5.75000  29.000000        1.000000   5.275000
50%    10.50000  32.500000        2.500000   6.650000
75%    15.25000  40.000000        5.000000   8.225000
max    20.00000  45.000000        8.000000   9.300000

In [32]:
# consultar los q tiene promedio mayor de 8 y esten activos
df[(df["promedio"]>=8) & (df["activo"]==True)]

    id           nombre  edad        ciudad  cursos_previos  promedio  activo
0    1      Laura Gómez    42      Medellín               0       8.3    True
4    5      María López    29     Manizales               4       8.8    True
7    8   Diego Martínez    33     Cartagena               0       8.2    True
14  15  Lucía Fernández    42  Barranquilla               5       9.0    True

In [ ]:
#motrar los que tiene promedio superior a 8, con activo true y ordenar por la edad de manera descendente
df[(df['promedio'] >= 8) & (df['activo'] == True)].sort_values(by='edad', ascending=False)

    id           nombre  edad        ciudad  cursos_previos  promedio  activo
0    1      Laura Gómez    42      Medellín               0       8.3    True
14  15  Lucía Fernández    42  Barranquilla               5       9.0    True
7    8   Diego Martínez    33     Cartagena               0       8.2    True
4    5      María López    29     Manizales               4       8.8    True

# Limpiar dataSet pero con criterio

Detectar → hay algun problema?

In [40]:
df.isnull().sum()

nombre                  0
edad                    0
ciudad                  0
pais                    0
genero                  0
nivel_previo            0
horas_estudio_semana    0
promedio                2
modulos_completados     0
activo                  0
fecha_ingreso           0
trabaja_actualmente     0
salario_usd             0
objetivo                0
dtype: int64